import type { ContactStatus, ActivityType, TaskType, TaskPriority } from './types'

export const englishTranslations = {
  app: {
    title: 'Customer Management',
    tagline: 'Manage your customers and sales',
  },
  nav: {
    dashboard: 'Dashboard',
    contacts: 'Contacts',
    pipeline: 'Pipeline',
    tasks: 'Tasks',
    reports: 'Reports',
  },
  contact: {
    title: 'Contacts',
    addNew: 'New contact',
    firstName: 'First name',
    lastName: 'Last name',
    email: 'Email',
    phone: 'Phone',
    company: 'Company',
    status: 'Status',
    tags: 'Tags',
    value: 'Value',
    source: 'Source',
    notes: 'Notes',
    createdAt: 'Created',
    updatedAt: 'Updated',
    all: 'All contacts',
    details: 'Contact details',
    edit: 'Edit contact',
    delete: 'Delete contact',
    deleteConfirm: 'Are you sure you want to delete this contact?',
  },
  status: {
    lead: 'Lead',
    prospect: 'Prospect',
    customer: 'Customer',
    lost: 'Lost',
  },
  deal: {
    title: 'Deal',
    addNew: 'New deal',
    dealTitle: 'Deal title',
    stage: 'Stage',
    value: 'Value (NOK)',
    probability: 'Probability',
    expectedCloseDate: 'Expected close date',
    description: 'Description',
    details: 'Deal details',
    edit: 'Edit deal',
    won: 'Won',
    lost: 'Lost',
    open: 'Open deals',
  },
  task: {
    title: 'Task',
    addNew: 'New task',
    taskTitle: 'Task title',
    description: 'Description',
    dueDate: 'Due date',
    priority: 'Priority',
    type: 'Type',
    completed: 'Completed',
    pending: 'Pending',
    overdue: 'Overdue',
    all: 'All tasks',
    markComplete: 'Mark as complete',
    markIncomplete: 'Mark as incomplete',
  },
  priority: {
    low: 'Low',
    medium: 'Medium',
    high: 'High',
  },
  taskType: {
    call: 'Phone call',
    email: 'Email',
    meeting: 'Meeting',
    'follow-up': 'Follow-up',
    other: 'Other',
  },
  activity: {
    title: 'Activities',
    addNew: 'Log activity',
    type: 'Type',
    subject: 'Subject',
    notes: 'Notes',
    duration: 'Duration (min)',
    outcome: 'Outcome',
    timeline: 'Timeline',
    recent: 'Recent activity',
  },
  activityType: {
    call: 'Call',
    email: 'Email',
    meeting: 'Meeting',
    note: 'Note',
    'status-change': 'Status change',
    'email-sent': 'Email sent',
    'email-opened': 'Email opened',
    'email-clicked': 'Email clicked',
  },
  email: {
    title: 'Email',
    compose: 'Compose email',
    send: 'Send',
    sendAndTrack: 'Send and track',
    sendNow: 'Send now',
    schedule: 'Schedule',
    to: 'To',
    cc: 'CC',
    bcc: 'BCC',
    subject: 'Subject',
    body: 'Message',
    attachments: 'Attachments',
    template: 'Template',
    templates: 'Email templates',
    newTemplate: 'New template',
    saveAsTemplate: 'Save as template',
    useTemplate: 'Use template',
    selectTemplate: 'Select template',
    draft: 'Draft',
    sent: 'Sent',
    failed: 'Failed',
    opened: 'Opened',
    clicked: 'Clicked',
    scheduled: 'Scheduled',
    trackingEnabled: 'Tracking enabled',
    openCount: 'Opens',
    clickCount: 'Clicks',
    sendSuccess: 'Email sent',
    sendError: 'Could not send email',
    scheduleFor: 'Schedule for',
    scheduleDate: 'Schedule date',
    scheduleTime: 'Schedule time',
    scheduleSuccess: 'Email scheduled',
    scheduledFor: 'Scheduled for',
    cancelSchedule: 'Cancel schedule',
    editScheduled: 'Edit scheduled',
    scheduleCancelled: 'Schedule cancelled',
    history: 'Email history',
    noEmails: 'No emails',
    templateSaved: 'Template saved',
    templateName: 'Template name',
    category: 'Category',
    recurring: 'Recurring',
    recurrencePattern: 'Recurrence pattern',
    recurrenceNone: 'None',
    recurrenceDaily: 'Daily',
    recurrenceWeekly: 'Weekly',
    recurrenceMonthly: 'Monthly',
    recurrenceInterval: 'Every',
    recurrenceEndDate: 'End date',
    recurrenceEndAfter: 'End after',
    recurrenceOccurrences: 'occurrences',
    recurrenceEnabled: 'Enable recurrence',
    recurrenceNext: 'Next send',
    recurrenceSeries: 'Recurring series',
    recurrenceCount: 'Sent',
    stopRecurrence: 'Stop recurrence',
    viewSeries: 'View series',
  },
  pipeline: {
    title: 'Sales pipeline',
    stages: 'Stages',
    totalValue: 'Total value',
    avgProbability: 'Avg. probability',
  },
  dashboard: {
    title: 'Dashboard',
    metrics: 'Key metrics',
    totalContacts: 'Total contacts',
    totalDeals: 'Total deals',
    totalRevenue: 'Total revenue',
    openDeals: 'Open deals',
    wonDeals: 'Won deals',
    lostDeals: 'Lost deals',
    averageDealValue: 'Average deal value',
    conversionRate: 'Conversion rate',
    recentActivity: 'Recent activity',
    upcomingTasks: 'Upcoming tasks',
  },
  common: {
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    close: 'Close',
    search: 'Search',
    filter: 'Filter',
    export: 'Export',
    import: 'Import',
    loading: 'Loading...',
    noResults: 'No results',
    confirm: 'Confirm',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    selectAll: 'Select all',
    clearAll: 'Clear all',
    addTag: 'Add tag',
    required: 'Required',
    optional: 'Optional',
    yes: 'Yes',
    no: 'No',
    success: 'Success',
    error: 'Error',
    importExport: 'Import/Export',
    exportVariables: 'Export variables',
    importVariables: 'Import variables',
  },
  api: {
    title: 'API Integrations',
    apiKeys: 'API Keys',
    webhooks: 'Webhooks',
    integrations: 'Integrations',
    newApiKey: 'New API key',
    newWebhook: 'New webhook',
    newIntegration: 'New integration',
    apiKeyName: 'API key name',
    apiKeyDescription: 'Description',
    permissions: 'Permissions',
    permissionRead: 'Read',
    permissionWrite: 'Write',
    permissionDelete: 'Delete',
    permissionAdmin: 'Administrator',
    resourcePermissions: 'Resource permissions',
    resourceContacts: 'Contacts',
    resourceDeals: 'Deals',
    resourceTasks: 'Tasks',
    resourceEmails: 'Emails',
    resourceWebhooks: 'Webhooks',
    resourceReports: 'Reports',
    resourceAll: 'All resources',
    advancedSettings: 'Advanced settings',
    rateLimit: 'Rate limit (per hour)',
    ipWhitelist: 'IP whitelist',
    ipWhitelistHelp: 'Comma-separated list of allowed IP addresses (optional)',
    customizePermissions: 'Customize permissions per resource',
    useBasicPermissions: 'Use basic permissions',
    expiresAt: 'Expires',
    neverExpires: 'Never expires',
    lastUsed: 'Last used',
    keyCreated: 'API key created',
    copyKey: 'Copy key',
    keyCopied: 'Key copied',
    keyWarning: 'This key will only be shown once. Store it securely.',
    revokeKey: 'Revoke key',
    keyRevoked: 'API key revoked',
    webhookName: 'Webhook name',
    webhookUrl: 'Webhook URL',
    events: 'Events',
    secret: 'Secret',
    active: 'Active',
    inactive: 'Inactive',
    lastTriggered: 'Last triggered',
    failureCount: 'Failures',
    testWebhook: 'Test webhook',
    webhookCreated: 'Webhook created',
    webhookUpdated: 'Webhook updated',
    webhookDeleted: 'Webhook deleted',
    webhookTested: 'Webhook tested',
    integrationType: 'Type',
    integrationProvider: 'Provider',
    integrationConfig: 'Configuration',
    lastSync: 'Last synced',
    syncNow: 'Sync now',
    integrationCreated: 'Integration created',
    integrationUpdated: 'Integration updated',
    integrationDeleted: 'Integration deleted',
    smtpHost: 'SMTP host',
    smtpPort: 'Port',
    smtpUsername: 'Username',
    smtpPassword: 'Password',
    smtpSecure: 'Secure connection (TLS)',
    smsApiKey: 'SMS API key',
    smsProvider: 'SMS provider',
    apiDocs: 'API Documentation',
    webhookLogs: 'Webhook logs',
    viewLogs: 'View logs',
    noLogs: 'No logs yet',
    logTimestamp: 'Timestamp',
    logEvent: 'Event',
    logStatus: 'Status',
    logResponse: 'Response',
    logResponseTime: 'Response time',
    statusSuccess: 'Success',
    statusFailed: 'Failed',
  },
  footer: {
    description: 'A modern CRM system for Norwegian businesses. Manage customers, sales, and tasks in one place.',
    product: 'Product',
    features: 'Features',
    pricing: 'Pricing',
    documentation: 'Documentation',
    changelog: 'Changelog',
    company: 'Company',
    about: 'About us',
    blog: 'Blog',
    careers: 'Careers',
    contact: 'Contact us',
    support: 'Support',
    helpCenter: 'Help Center',
    communityForum: 'Community',
    legal: 'Legal',
    privacy: 'Privacy',
    terms: 'Terms',
    gdpr: 'GDPR Compliance',
    security: 'Security',
    allRightsReserved: 'All rights reserved',
    madeIn: 'Made in Norway with',
    version: 'Version',
    language: 'Language',
  },
}

export const statusLabels: Record<ContactStatus, string> = {
  lead: englishTranslations.status.lead,
  prospect: englishTranslations.status.prospect,
  customer: englishTranslations.status.customer,
  lost: englishTranslations.status.lost,
}

export const activityTypeLabels: Record<ActivityType, string> = {
  call: englishTranslations.activityType.call,
  email: englishTranslations.activityType.email,
  meeting: englishTranslations.activityType.meeting,
  note: englishTranslations.activityType.note,
  'status-change': englishTranslations.activityType['status-change'],
  'email-sent': englishTranslations.activityType['email-sent'],
  'email-opened': englishTranslations.activityType['email-opened'],
  'email-clicked': englishTranslations.activityType['email-clicked'],
}

export const taskTypeLabels: Record<TaskType, string> = {
  call: englishTranslations.taskType.call,
  email: englishTranslations.taskType.email,
  meeting: englishTranslations.taskType.meeting,
  'follow-up': englishTranslations.taskType['follow-up'],
  other: englishTranslations.taskType.other,
}

export const priorityLabels: Record<TaskPriority, string> = {
  low: englishTranslations.priority.low,
  medium: englishTranslations.priority.medium,
  high: englishTranslations.priority.high,
}

export const defaultPipelineStages = [
  { id: 'first-contact', name: 'First contact', order: 0, probability: 20, color: 'oklch(0.75 0.15 80)' },
  { id: 'qualification', name: 'Qualification', order: 1, probability: 40, color: 'oklch(0.70 0.12 230)' },
  { id: 'proposal', name: 'Proposal sent', order: 2, probability: 60, color: 'oklch(0.65 0.12 250)' },
  { id: 'negotiation', name: 'Negotiation', order: 3, probability: 80, color: 'oklch(0.60 0.15 160)' },
  { id: 'won', name: 'Won', order: 4, probability: 100, color: 'oklch(0.65 0.15 160)' },
  { id: 'lost', name: 'Lost', order: 5, probability: 0, color: 'oklch(0.60 0.15 25)' },
]
