import type { ContactStatus, ActivityType, TaskType, TaskPriority } from './types'

export const norwegianTranslations = {
  app: {
    title: 'Kundeadministrasjon',
    tagline: 'Administrer dine kunder og salg',
  },
  nav: {
    dashboard: 'Oversikt',
    contacts: 'Kontakter',
    pipeline: 'Salgstrakt',
    tasks: 'Oppgaver',
    reports: 'Rapporter',
  },
  contact: {
    title: 'Kontakter',
    addNew: 'Ny kontakt',
    firstName: 'Fornavn',
    lastName: 'Etternavn',
    email: 'E-post',
    phone: 'Telefon',
    company: 'Selskap',
    status: 'Status',
    tags: 'Tagger',
    value: 'Verdi',
    source: 'Kilde',
    notes: 'Notater',
    createdAt: 'Opprettet',
    updatedAt: 'Oppdatert',
    all: 'Alle kontakter',
    details: 'Kontaktdetaljer',
    edit: 'Rediger kontakt',
    delete: 'Slett kontakt',
    deleteConfirm: 'Er du sikker på at du vil slette denne kontakten?',
    noContacts: 'Ingen kontakter enda',
    addFirstContact: 'Begynn med å legge til din første kontakt',
    updated: 'Kontakt oppdatert',
    created: 'Kontakt opprettet',
    deleted: 'Kontakt slettet',
    unknown: 'Ukjent kontakt',
    selectContact: 'Velg kontakt (valgfritt)',
    noContact: 'Ingen kontakt',
  },
  status: {
    lead: 'Lead',
    prospect: 'Prospekt',
    customer: 'Kunde',
    lost: 'Tapt',
  },
  deal: {
    title: 'Avtale',
    addNew: 'Ny avtale',
    dealTitle: 'Avtaletittel',
    stage: 'Fase',
    value: 'Verdi (NOK)',
    probability: 'Sannsynlighet',
    expectedCloseDate: 'Forventet lukkedato',
    description: 'Beskrivelse',
    details: 'Avtaledetaljer',
    edit: 'Rediger avtale',
    won: 'Vunnet',
    lost: 'Tapt',
    open: 'Åpne avtaler',
    contact: 'Kontakt',
    selectContact: 'Velg kontakt',
    selectContactError: 'Velg en kontakt',
  },
  task: {
    title: 'Oppgave',
    addNew: 'Ny oppgave',
    taskTitle: 'Oppgavetittel',
    description: 'Beskrivelse',
    dueDate: 'Forfallsdato',
    priority: 'Prioritet',
    type: 'Type',
    completed: 'Fullført',
    pending: 'Ventende',
    overdue: 'Forfalt',
    all: 'Alle oppgaver',
    markComplete: 'Merk som fullført',
    markIncomplete: 'Merk som ufullført',
    created: 'Oppgave opprettet',
    noTasks: 'Ingen oppgaver',
    markedIncomplete: 'Oppgave markert som ufullført',
    markedComplete: 'Oppgave fullført!',
    deleted: 'Oppgave slettet',
    today: 'I dag',
  },
  priority: {
    low: 'Lav',
    medium: 'Middels',
    high: 'Høy',
  },
  taskType: {
    call: 'Telefonsamtale',
    email: 'E-post',
    meeting: 'Møte',
    'follow-up': 'Oppfølging',
    other: 'Annet',
  },
  activity: {
    title: 'Aktiviteter',
    addNew: 'Logg aktivitet',
    type: 'Type',
    subject: 'Emne',
    notes: 'Notater',
    duration: 'Varighet (min)',
    outcome: 'Resultat',
    timeline: 'Tidslinje',
    recent: 'Nylig aktivitet',
  },
  activityType: {
    call: 'Samtale',
    email: 'E-post',
    meeting: 'Møte',
    note: 'Notat',
    'status-change': 'Statusendring',
    'email-sent': 'E-post sendt',
    'email-opened': 'E-post åpnet',
    'email-clicked': 'E-post klikket',
  },
  email: {
    title: 'E-post',
    compose: 'Skriv e-post',
    send: 'Send',
    sendAndTrack: 'Send og spor',
    sendNow: 'Send nå',
    schedule: 'Planlegg sending',
    to: 'Til',
    cc: 'Kopi',
    bcc: 'Blindkopi',
    subject: 'Emne',
    body: 'Melding',
    attachments: 'Vedlegg',
    template: 'Mal',
    templates: 'E-postmaler',
    newTemplate: 'Ny mal',
    saveAsTemplate: 'Lagre som mal',
    useTemplate: 'Bruk mal',
    selectTemplate: 'Velg mal',
    draft: 'Utkast',
    sent: 'Sendt',
    failed: 'Feilet',
    opened: 'Åpnet',
    clicked: 'Klikket',
    scheduled: 'Planlagt',
    trackingEnabled: 'Sporing aktivert',
    openCount: 'Antall åpninger',
    clickCount: 'Antall klikk',
    sendSuccess: 'E-post sendt',
    sendError: 'Kunne ikke sende e-post',
    scheduleFor: 'Planlegg for',
    scheduleDate: 'Planlagt dato',
    scheduleTime: 'Planlagt tid',
    scheduleSuccess: 'E-post planlagt',
    scheduledFor: 'Planlagt til',
    cancelSchedule: 'Avbryt planlegging',
    editScheduled: 'Rediger planlagt',
    scheduleCancelled: 'Planlegging avbrutt',
    history: 'E-posthistorikk',
    noEmails: 'Ingen e-poster',
    templateSaved: 'Mal lagret',
    templateName: 'Malnavn',
    category: 'Kategori',
    recurring: 'Gjentakende',
    recurrencePattern: 'Gjentagelsesmønster',
    recurrenceNone: 'Ingen',
    recurrenceDaily: 'Daglig',
    recurrenceWeekly: 'Ukentlig',
    recurrenceMonthly: 'Månedlig',
    recurrenceInterval: 'Hvert',
    recurrenceEndDate: 'Sluttdato',
    recurrenceEndAfter: 'Avslutt etter',
    recurrenceOccurrences: 'forekomster',
    recurrenceEnabled: 'Aktiver gjentakelse',
    recurrenceNext: 'Neste sending',
    recurrenceSeries: 'Gjentakende serie',
    recurrenceCount: 'Sendt',
    stopRecurrence: 'Stopp gjentakelse',
    viewSeries: 'Vis serie',
    sendAndTrackMessage: 'Send og spor e-poster til dine kunder',
  },
  pipeline: {
    title: 'Salgstrakt',
    stages: 'Faser',
    totalValue: 'Total verdi',
    avgProbability: 'Gj.snitt sannsynlighet',
  },
  dashboard: {
    title: 'Oversikt',
    metrics: 'Nøkkeltall',
    totalContacts: 'Totalt antall kontakter',
    totalDeals: 'Totalt antall avtaler',
    totalRevenue: 'Total omsetning',
    openDeals: 'Åpne avtaler',
    wonDeals: 'Vunnede avtaler',
    lostDeals: 'Tapte avtaler',
    averageDealValue: 'Gjennomsnittlig avtaleverdi',
    conversionRate: 'Konverteringsrate',
    recentActivity: 'Nylig aktivitet',
    upcomingTasks: 'Kommende oppgaver',
    callsThisWeek: 'Samtaler denne uken',
    emailsThisWeek: 'E-poster denne uken',
    meetingsThisWeek: 'Møter denne uken',
    emailsSent: 'E-poster sendt',
    openRate: 'Åpningsrate',
    clickRate: 'Klikkrate',
    opened: 'åpnet',
    clicked: 'klikket',
    additionalStats: 'Ytterligere statistikk',
    pendingTasks: 'Ventende oppgaver',
    contactStatus: 'Kontaktstatus',
    welcomeTitle: 'Velkommen til Norwegian CRM!',
    welcomeMessage: 'Begynn med å legge til dine første kontakter og avtaler. Gå til "Kontakter" for å starte.',
    of: 'av',
  },
  common: {
    save: 'Lagre',
    cancel: 'Avbryt',
    delete: 'Slett',
    edit: 'Rediger',
    close: 'Lukk',
    view: 'Vis',
    search: 'Søk',
    filter: 'Filtrer',
    export: 'Eksporter',
    import: 'Importer',
    loading: 'Laster...',
    noResults: 'Ingen resultater',
    confirm: 'Bekreft',
    back: 'Tilbake',
    next: 'Neste',
    previous: 'Forrige',
    selectAll: 'Velg alle',
    clearAll: 'Fjern alle',
    addTag: 'Legg til tag',
    required: 'Påkrevd',
    optional: 'Valgfritt',
    yes: 'Ja',
    no: 'Nei',
    success: 'Vellykket',
    error: 'Feil',
    importExport: 'Importer/Eksporter',
    exportVariables: 'Eksporter variabler',
    importVariables: 'Importer variabler',
    exportToCSV: 'Eksporter til CSV',
    exportContacts: 'Eksporter kontakter',
    exportDeals: 'Eksporter avtaler',
    exportSuccess: 'Data eksportert',
    done: 'Ferdig',
  },
  import: {
    title: 'Importer fra CSV',
    description: 'Last opp en CSV-fil for å importere data',
    downloadTemplate: 'Last ned mal',
    dragDrop: 'Dra og slipp CSV-fil her',
    browseFiles: 'Velg fil',
    csvOnly: 'Kun CSV-filer (.csv)',
    importing: 'Importerer...',
    importSuccess: 'Import vellykket',
    importFailed: 'Import mislyktes',
    imported: 'Importert',
    skipped: 'Hoppet over',
    errors: 'Feil',
    row: 'Rad',
    invalidFileType: 'Ugyldig filtype. Kun CSV-filer er tillatt.',
    importAnother: 'Importer en annen fil',
    importContacts: 'Importer kontakter',
    importDeals: 'Importer avtaler',
    importContactsDesc: 'Last opp en CSV-fil med kontakter. Påkrevde felt: fornavn, etternavn.',
    importDealsDesc: 'Last opp en CSV-fil med avtaler. Påkrevde felt: tittel, kontakt-ID, fase, verdi.',
  },
  api: {
    title: 'API-integrasjoner',
    apiKeys: 'API-nøkler',
    webhooks: 'Webhooks',
    integrations: 'Integrasjoner',
    newApiKey: 'Ny API-nøkkel',
    newWebhook: 'Ny webhook',
    newIntegration: 'Ny integrasjon',
    apiKeyName: 'Navn på API-nøkkel',
    apiKeyDescription: 'Beskrivelse',
    permissions: 'Tillatelser',
    permissionRead: 'Les',
    permissionWrite: 'Skriv',
    permissionDelete: 'Slett',
    permissionAdmin: 'Administrator',
    resourcePermissions: 'Ressurstillatelser',
    resourceContacts: 'Kontakter',
    resourceDeals: 'Avtaler',
    resourceTasks: 'Oppgaver',
    resourceEmails: 'E-poster',
    resourceWebhooks: 'Webhooks',
    resourceReports: 'Rapporter',
    resourceAll: 'Alle ressurser',
    advancedSettings: 'Avanserte innstillinger',
    rateLimit: 'Forespørselsgrense (per time)',
    ipWhitelist: 'IP-hviteliste',
    ipWhitelistHelp: 'Kommaseparert liste med tillatte IP-adresser (valgfritt)',
    customizePermissions: 'Tilpass tillatelser per ressurs',
    useBasicPermissions: 'Bruk grunnleggende tillatelser',
    expiresAt: 'Utløper',
    neverExpires: 'Utløper aldri',
    lastUsed: 'Sist brukt',
    keyCreated: 'API-nøkkel opprettet',
    copyKey: 'Kopier nøkkel',
    keyCopied: 'Nøkkel kopiert',
    keyWarning: 'Denne nøkkelen vises bare én gang. Lagre den på et sikkert sted.',
    revokeKey: 'Tilbakekall nøkkel',
    keyRevoked: 'API-nøkkel tilbakekalt',
    webhookName: 'Webhook-navn',
    webhookUrl: 'Webhook-URL',
    events: 'Hendelser',
    secret: 'Hemmelig nøkkel',
    active: 'Aktiv',
    inactive: 'Inaktiv',
    lastTriggered: 'Sist utløst',
    failureCount: 'Feilantall',
    testWebhook: 'Test webhook',
    webhookCreated: 'Webhook opprettet',
    webhookUpdated: 'Webhook oppdatert',
    webhookDeleted: 'Webhook slettet',
    webhookTested: 'Webhook testet',
    integrationType: 'Type',
    integrationProvider: 'Leverandør',
    integrationConfig: 'Konfigurasjon',
    lastSync: 'Sist synkronisert',
    syncNow: 'Synkroniser nå',
    integrationCreated: 'Integrasjon opprettet',
    integrationUpdated: 'Integrasjon oppdatert',
    integrationDeleted: 'Integrasjon slettet',
    smtpHost: 'SMTP-server',
    smtpPort: 'Port',
    smtpUsername: 'Brukernavn',
    smtpPassword: 'Passord',
    smtpSecure: 'Sikker forbindelse (TLS)',
    smsApiKey: 'SMS API-nøkkel',
    smsProvider: 'SMS-leverandør',
    apiDocs: 'API-dokumentasjon',
    webhookLogs: 'Webhook-logger',
    viewLogs: 'Vis logger',
    noLogs: 'Ingen logger ennå',
    logTimestamp: 'Tidspunkt',
    logEvent: 'Hendelse',
    logStatus: 'Status',
    logResponse: 'Respons',
    logResponseTime: 'Responstid',
    statusSuccess: 'Vellykket',
    statusFailed: 'Feilet',
    manageMessage: 'Administrer API-nøkler, webhooks og eksterne integrasjoner',
  },
  footer: {
    description: 'Et moderne CRM-system for norske bedrifter. Administrer kunder, salg og oppgaver på ett sted.',
    product: 'Produkt',
    features: 'Funksjoner',
    pricing: 'Priser',
    documentation: 'Dokumentasjon',
    changelog: 'Endringslogg',
    company: 'Selskap',
    about: 'Om oss',
    blog: 'Blogg',
    careers: 'Karriere',
    contact: 'Kontakt oss',
    support: 'Støtte',
    helpCenter: 'Hjelpesenter',
    communityForum: 'Fellesskap',
    legal: 'Juridisk',
    privacy: 'Personvern',
    terms: 'Vilkår',
    gdpr: 'GDPR-samsvar',
    security: 'Sikkerhet',
    allRightsReserved: 'Alle rettigheter reservert',
    madeIn: 'Laget i Norge med',
    version: 'Versjon',
    language: 'Språk',
  },
  team: {
    title: 'Team',
    members: 'Teammedlemmer',
    addMember: 'Legg til medlem',
    inviteMember: 'Inviter medlem',
    editMember: 'Rediger medlem',
    removeMember: 'Fjern medlem',
    removeConfirm: 'Er du sikker på at du vil fjerne dette teammedlemmet?',
    role: 'Rolle',
    department: 'Avdeling',
    jobTitle: 'Stillingstittel',
    status: 'Status',
    active: 'Aktiv',
    inactive: 'Inaktiv',
    lastActive: 'Sist aktiv',
    invitedAt: 'Invitert',
    memberCreated: 'Teammedlem lagt til',
    memberUpdated: 'Teammedlem oppdatert',
    memberRemoved: 'Teammedlem fjernet',
    noMembers: 'Ingen teammedlemmer enda',
    addFirstMember: 'Begynn med å invitere ditt første teammedlem',
    permissions: 'Tillatelser',
    rolePermissions: 'Rolletillatelser',
    viewPermissions: 'Vis tillatelser',
    manageTeam: 'Administrer team og tillatelser',
    activateAccount: 'Aktiver konto',
    deactivateAccount: 'Deaktiver konto',
    accountActivated: 'Konto aktivert',
    accountDeactivated: 'Konto deaktivert',
  },
  roles: {
    admin: 'Administrator',
    manager: 'Leder',
    sales: 'Selger',
  },
  roleDescriptions: {
    admin: 'Full tilgang til alle funksjoner og innstillinger',
    manager: 'Administrer team, se alle data, administrer innstillinger',
    sales: 'Administrer egne kontakter, avtaler og oppgaver',
  },
  permissions: {
    view: 'Vis',
    create: 'Opprett',
    edit: 'Rediger',
    delete: 'Slett',
    viewAll: 'Vis alle',
    exportData: 'Eksporter data',
    importData: 'Importer data',
    reassign: 'Tilordne på nytt',
    send: 'Send',
    manageTemplates: 'Administrer maler',
    export: 'Eksporter',
    manage: 'Administrer',
    invite: 'Inviter',
    remove: 'Fjern',
    changeRoles: 'Endre roller',
    contacts: 'Kontakter',
    deals: 'Avtaler',
    tasks: 'Oppgaver',
    emails: 'E-poster',
    reports: 'Rapporter',
    api: 'API',
    team: 'Team',
  },
  auth: {
    login: 'Logg inn',
    logout: 'Logg ut',
    email: 'E-post',
    password: 'Passord',
    loginDescription: 'Skriv inn påloggingsinformasjonen din for å få tilgang til CRM',
    fillAllFields: 'Vennligst fyll ut alle feltene',
    loginSuccess: 'Innlogging vellykket',
    invalidCredentials: 'Ugyldig e-post eller passord',
    loginError: 'En feil oppstod under innlogging',
    loggingIn: 'Logger inn...',
    demoAccounts: 'Demo-kontoer:',
    anyPassword: 'Passord: hvilken som helst verdi',
    demoPassword: 'Passord: demo123',
    accessDenied: 'Tilgang nektet',
    noPermission: 'Du har ikke tillatelse til å få tilgang til denne funksjonen.',
    forgotPassword: 'Glemt passord?',
    resetPassword: 'Tilbakestill passord',
    resetPasswordDescription: 'Skriv inn e-postadressen din, så sender vi deg en lenke for tilbakestilling',
    sendResetLink: 'Send tilbakestillingslenke',
    resetLinkSent: 'Tilbakestillingslenke sendt til e-posten din',
    resetLinkSentDescription: 'Sjekk e-posten din for instruksjoner om hvordan du tilbakestiller passordet ditt',
    backToLogin: 'Tilbake til pålogging',
    newPassword: 'Nytt passord',
    confirmPassword: 'Bekreft passord',
    passwordsDoNotMatch: 'Passordene stemmer ikke overens',
    passwordResetSuccess: 'Passord tilbakestilt vellykket',
    passwordResetError: 'Kunne ikke tilbakestille passord',
    invalidResetToken: 'Ugyldig eller utløpt tilbakestillingslenke',
    resetting: 'Tilbakestiller...',
    emailVerification: 'E-postverifisering',
    verifyEmail: 'Bekreft e-post',
    emailNotVerified: 'E-posten din er ikke bekreftet',
    emailNotVerifiedDescription: 'Sjekk innboksen din for verifiseringse-posten',
    resendVerification: 'Send verifiseringse-post på nytt',
    verificationSent: 'Verifiseringse-post sendt',
    verificationSuccess: 'E-post bekreftet vellykket',
    verificationError: 'Kunne ikke bekrefte e-post',
    invalidVerificationToken: 'Ugyldig eller utløpt verifiseringslenke',
    verifying: 'Bekrefter...',
    emailVerified: 'E-post bekreftet',
  },
}

export const statusLabels: Record<ContactStatus, string> = {
  lead: norwegianTranslations.status.lead,
  prospect: norwegianTranslations.status.prospect,
  customer: norwegianTranslations.status.customer,
  lost: norwegianTranslations.status.lost,
}

export const activityTypeLabels: Record<ActivityType, string> = {
  call: norwegianTranslations.activityType.call,
  email: norwegianTranslations.activityType.email,
  meeting: norwegianTranslations.activityType.meeting,
  note: norwegianTranslations.activityType.note,
  'status-change': norwegianTranslations.activityType['status-change'],
  'email-sent': norwegianTranslations.activityType['email-sent'],
  'email-opened': norwegianTranslations.activityType['email-opened'],
  'email-clicked': norwegianTranslations.activityType['email-clicked'],
}

export const taskTypeLabels: Record<TaskType, string> = {
  call: norwegianTranslations.taskType.call,
  email: norwegianTranslations.taskType.email,
  meeting: norwegianTranslations.taskType.meeting,
  'follow-up': norwegianTranslations.taskType['follow-up'],
  other: norwegianTranslations.taskType.other,
}

export const priorityLabels: Record<TaskPriority, string> = {
  low: norwegianTranslations.priority.low,
  medium: norwegianTranslations.priority.medium,
  high: norwegianTranslations.priority.high,
}

export const defaultPipelineStages = [
  { id: 'first-contact', name: 'Første kontakt', order: 0, probability: 20, color: 'oklch(0.75 0.15 80)' },
  { id: 'qualification', name: 'Kvalifisering', order: 1, probability: 40, color: 'oklch(0.70 0.12 230)' },
  { id: 'proposal', name: 'Tilbud sendt', order: 2, probability: 60, color: 'oklch(0.65 0.12 250)' },
  { id: 'negotiation', name: 'Forhandling', order: 3, probability: 80, color: 'oklch(0.60 0.15 160)' },
  { id: 'won', name: 'Vunnet', order: 4, probability: 100, color: 'oklch(0.65 0.15 160)' },
  { id: 'lost', name: 'Tapt', order: 5, probability: 0, color: 'oklch(0.60 0.15 25)' },
]
